services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y r-base
      Rscript --version  # Comando para verificar que Rscript está disponible
      pip install -r requirements.txt
    startCommand: gunicorn app:app
